### ISSUE TITLE
Faltam dados no README

### ISSUE THREAD

**Issue by JhonnyBn** [PET-SI-UFU/PrimeiroPR#1]
Basta o que?
![image](https://user-images.githubusercontent.com/29382833/153609351-b3b452fd-7186-4cb3-88f9-fa28d8e9d17e.png)

**Comment by PET-SI-UFU** [comment]
Tem razão. Estamos aceitando PRs para resolver este problema

**Comment by JhonnyBn** [comment]
PR para resolver este issue: #2

**Comment by PET-SI-UFU** [comment]
Muito obrigado. Merge #2
